### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Gioherk** [SerpentDrago/SerenTheme-SerenMod-Full#6]
Not working any more.
Please fix it

**Comment by SerpentDrago** [comment]
#5

**Comment by Gioherk** [comment]
Why did you closed the issue without fixing it?

**Comment by drinfernoo** [comment]
Why did you open such a vague issue? There's no way to know why it's not working for you, or what the fix to *your* issue is.

**Comment by SerpentDrago** [comment]
> Why did you closed the issue without fixing it?

it is fixed , noticed i even linked to the PR that fixed it . it works fine
