### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Gioherk** [SerpentDrago/SerenTheme-SerenMod-Full#7]
Why did you closed the issue?

**Comment by drinfernoo** [comment]
It doesn't really help to open these issues with no information. This theme works fine with Seren 2.0.8.

**Comment by Gioherk** [comment]
Not, to me it doesn't work.
Tomorrow I will post a log.

**Comment by SerpentDrago** [comment]
It works fine , i've had multiple people test it , you should prob uninstall the theme and reinstall it fresh following the instructions.

You need to be sure your using auramod obviously as this theme only works with auramod . 

But better yet you should just stick to seren 2.0 stock theme , as it has more features . if ALL you want is Themed Upnext/still watching popups , i have mod of seren 2. 0 stock that adds the themed nice looking upnext popups from this theme . 

https://github.com/SerpentDrago/SerenTheme-SerenMod-Full/blob/serenstockmod/README.md
