### ISSUE TITLE
Source select view

### ISSUE THREAD

**Issue by SirRickie** [SerpentDrago/SerenTheme-SerenMod-Full#9]
Just a small question : in the source select view, in your screenshot the links are numbered 1)2)3) ... which is very useful. I installed your theme on Auramod skin, but the numbers are not there (see screenshot). Can this be fixed ? Tnx.
![New Image](https://user-images.githubusercontent.com/60318531/107029469-581a7a00-67af-11eb-9fea-d8636bb8097b.jpg)

**Comment by SerpentDrago** [comment]
sorry dont' really mess with this anymore , your welcome to submit PR  (pull request) to add this / fix it .  and i'll review and accept
